CHARACTER_DICT: dict[str, list[list[bool]]] = {
    "A": [
        [False, True, False],
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
    ],
    "B": [
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, True, False],
    ],
    "C": [
        [False, True, True],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [False, True, True],
    ],
    "D": [
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, False],
    ],
    "E": [
        [True, True, True],
        [True, False, False],
        [True, False, False],
        [True, True, False],
        [True, False, False],
        [True, False, False],
        [True, True, True],
    ],
    "F": [
        [True, True, True],
        [True, False, False],
        [True, False, False],
        [True, True, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
    ],
    "G": [
        [False, True, True],
        [True, False, False],
        [True, False, False],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, True],
    ],
    "H": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
    ],
    "I": [
        [True, True, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [True, True, True],
    ],
    "J": [
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [True, False, True],
        [False, True, False],
    ],
    "K": [
        [True, False, True],
        [True, False, True],
        [True, True, False],
        [True, False, False],
        [True, True, False],
        [True, False, True],
        [True, False, True],
    ],
    "L": [
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, True, True],
    ],
    "M": [
        [True, False, True],
        [True, True, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
    ],
    "N": [
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
    ],
    "O": [
        [False, True, False],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, False],
    ],
    "P": [
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, True, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
    ],
    "Q": [
        [False, True, False],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, True],
        [False, False, True],
    ],
    "R": [
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, True, False],
        [True, True, False],
        [True, False, True],
        [True, False, True],
    ],
    "S": [
        [False, True, True],
        [True, False, False],
        [True, False, False],
        [False, True, False],
        [False, False, True],
        [False, False, True],
        [True, True, False],
    ],
    "T": [
        [True, True, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
    ],
    "U": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, False],
    ],
    "V": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, False],
    ],
    "W": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, True, True],
        [True, False, True],
    ],
    "X": [
        [True, False, True],
        [True, False, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [True, False, True],
        [True, False, True],
    ],
    "Y": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
    ],
    "Z": [
        [True, True, True],
        [False, False, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [True, False, False],
        [True, True, True],
    ],
    " ": [
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
    ],
}
